Merged with current sdboot-manage from original repo

diff --git a/sdboot-manage b/sdboot-manage
--- a/sdboot-manage
+++ b/sdboot-manage
@@ -1,9 +1,47 @@
 #! /bin/bash
-#CUSTOM
+#
 # sdboot-manage provides automation for systemd-boot on systems with multiple kernels
 
-config=/etc/sdboot-manage.conf
-bootctl=/usr/bin/bootctl
+usage() {
+    echo "Usage: sdboot-manage [options] [action]"
+    echo ""
+    echo "Actions:"
+    echo "  gen     generates entries for systemd-boot based on installed kernels"
+    echo "  remove  removes orphaned systemd-boot entries"
+    echo "  setup   installs systemd-boot and generate initial entries"
+    echo "  update  updates systemd-boot"
+    echo ""
+    echo "Options:"
+    echo "  -e,--esp-path=<path>  specify <path> to be used for esp"
+    echo "  -c,--config=<path>    location of config file"
+    exit 1
+}
+
+# parse the options
+for i in "$@"; do
+    case $i in
+        -e=*|--esp-path=*)
+            ESP="${i#*=}"
+            shift
+        ;;
+        -c=*|--config=*)
+            config="${i#*=}"
+            shift
+        ;;
+        # handle unknown options
+        -*)
+            usage
+        ;;
+        # printing usage is handled later
+        *)
+            true
+        ;;
+    esac
+done
+
+# set defaults for optional arguments if they are not passed on the command-line
+[[ -z ${ESP} ]] && ESP=$(bootctl -p)
+[[ -z ${config} ]] && config=/etc/sdboot-manage.conf
 
 # config variables
 export  LINUX_OPTIONS \
@@ -21,21 +59,10 @@ export  LINUX_OPTIONS \
         NO_AUTOGEN \
         NO_AUTOUPDATE \
         CDISCARD \
-        DISCARD 
+        DISCARD
 
 # Load the config file
 [[ -f ${config} ]] && . "${config}"
-
-usage() {
-    echo "Usage: sdboot-manage [action]"
-    echo ""
-    echo "Actions:"
-    echo "  gen     generates entries for systemd-boot based on installed kernels"
-    echo "  remove  removes orphaned systemd-boot entries"
-    echo "  setup   installs systemd-boot and generate initial entries"
-    echo "  update  updates systemd-boot"
-    exit 1
-}
 
 get_entry_root() {
     echo -n "$1/loader/entries/${ENTRY_ROOT}"
@@ -46,21 +73,20 @@ get_entry_root() {
 
 # removes a systemd-boot entry
 remove_entry() {
-    [[ ${1} =~ ^$(get_entry_root "${esp}").* || ${PRESERVE_FOREIGN} != "yes" ]] && rm "$1"
+    [[ ${1} =~ ^$(get_entry_root "${ESP}").* || ${PRESERVE_FOREIGN} != "yes" ]] && rm "$1"
 }
 
 # installs and configures systemd-boot
 setup_sdboot() {
-    if $bootctl status &> /dev/null; then
+    if bootctl status &> /dev/null; then
         echo -e "systemd-boot already installed"
         exit 1
     else
-        # install systemd-boot letting it detect esp
-        $bootctl install
+        # install systemd-boot
+        bootctl --esp-path=${ESP} install
 
         # create a simple loader.conf
-        esp=$(bootctl -p)
-        echo "timeout 3" > "${esp}/loader/loader.conf"
+        echo "timeout 3" > "${ESP}/loader/loader.conf"
 
         # generate entries, ensure an initial set of entries is generated
         [[ ${DEFAULT_ENTRY} != "oldest" ]] && DEFAULT_ENTRY="latest"
@@ -69,21 +95,18 @@ setup_sdboot() {
 }
 
 generate_entries() {
-    # get the esp path
-    esp=$(bootctl -p)
     root='/'
 
-    echo "Generating ..."
-
     # First, ensure we have a valid config
-    if [[ -f ${esp}/loader/loader.conf ]]; then
+    if [[ -f ${ESP}/loader/loader.conf ]]; then
         # only build entries if there is some place to put them
-        if [[ -d ${esp}/loader/entries ]]; then
+        if [[ -d ${ESP}/loader/entries ]]; then
             srcdev=$(findmnt -no SOURCE ${root})
             srcdev_uuid=$(findmnt -no UUID ${root})
             srcdev_partuuid=$(findmnt -no PARTUUID ${root})
             srcdev_fsroot=$(findmnt -no FSROOT ${root})
             root_fstype=$(findmnt -no FSTYPE ${root})
+            mkinitcpio_has_sdencrypt_hook=$(grep -c '^HOOKS=\(.*sd-encrypt.*\)$' /etc/mkinitcpio.conf)
 
             # generate an appropriate options line
             case ${root_fstype} in
@@ -129,9 +152,19 @@ generate_entries() {
             while read -r devname devtype; do
                 if [[ $devtype == crypt ]]; then
                     # handle cryptdevice
-                    sdoptions="${sdoptions} cryptdevice=UUID=$(blkid -o value -s UUID "$(cryptsetup status "${devname}" | grep device | awk '{print $2}')"):${devname}"
+                    cryptdevice_option_prefix="cryptdevice=UUID"
+                    cryptdevice_option_suffix=":"
+                    if [[ ${mkinitcpio_has_sdencrypt_hook} > 0 ]]; then
+                        cryptdevice_option_prefix="rd.luks.name"
+                        cryptdevice_option_suffix="="
+                    fi
+                    sdoptions="${sdoptions} ${cryptdevice_option_prefix}=$(blkid -o value -s UUID "$(cryptsetup status "${devname}" | grep device | awk '{print $2}')")${cryptdevice_option_suffix}${devname}"
                     if [[ ${DISCARD,,} == "yes" ]]; then
-                        sdoptions="${sdoptions}:allow-discard"
+                        if [[ ${mkinitcpio_has_sdencrypt_hook} > 0 ]]; then
+                            sdoptions="${sdoptions} rd.luks.options=discard"
+                        else
+                            sdoptions="${sdoptions}:allow-discards"
+                        fi
                     fi
                 fi
             done < <(lsblk -nslo NAME,TYPE /dev/disk/by-uuid/"${top_level_uuid}" 2> /dev/null)
@@ -156,13 +189,13 @@ generate_entries() {
                 # if located in EFI, make sure to grab the Manjaro version
                 [[ $ucodefile =~ ^"${esp}/EFI/" ]] && { ! echo "${ucodefile}" | grep -iq "${ENTRY_ROOT}"; } && continue
                 ucode="${ucode}initrd\t${ucodefile}\n"
-            done < <(find "${esp}" -maxdepth 6 -type f -iname "*ucode.img" -printf "/%P\n")
+            done < <(find "${ESP}" -maxdepth 4 -type f -iname "*ucode.img" -printf "/%P\n")
 
             # when remove existing is set we want to start from an empty slate
             if [[ ${REMOVE_EXISTING,,} == "yes" ]]; then
                 while read -r entry; do
                     remove_entry "${entry}"
-                done < <(find "${esp}/loader/entries" -type f -name "*.conf")
+                done < <(find "${ESP}/loader/entries" -type f -name "*.conf")
             fi
 
             # create entries for each installed kernel
@@ -170,39 +203,45 @@ generate_entries() {
                 kernelnum=$(basename -- "${kernel}" | awk -F- '{print $2}')
                 arch=$(basename -- "${kernel}" | awk -F- '{print $3}')
 
-                # if installed in EFI, where multiple distro's can reside, check if distro is Manjaro
+                # if installed in EFI, where multiple distro's can reside, check if distro is Manjaro, if not continue
                 [[ $kernel =~ ^"${esp}/EFI/" ]] && { ! echo "${kernel}" | grep -iq "${ENTRY_ROOT}"; } && continue
 
                 # first validate we don't already have an entry for this kernel
-                [[ ${OVERWRITE_EXISTING,,} != "yes" && -f $(get_entry_root "$esp" "$kernelnum")${kernelnum}.conf ]] && continue
+                [[ ${OVERWRITE_EXISTING,,} != "yes" && -f $(get_entry_root "$ESP" "$kernelnum")${kernelnum}.conf ]] && continue
 
                 title=${ENTRY_TITLE}
                 if [[ ${ENTRY_APPEND_KVER,,} == "yes" ]]; then
                     title="${title} ${kernelnum}"
                 fi
 
-                initramfs=$(find "${esp}" -maxdepth 5 -type f -name "initramfs-${kernelnum}-${arch}.img" -printf "/%P\n")
-                initramfs_fallback=$(find "${esp}" -maxdepth 5 -type f -name "initramfs-${kernelnum}-${arch}-fallback.img" -printf "/%P\n")
+                # get the kernel location so the initrd can be written to the same location as the kernel
+                [[ $(dirname ${kernel}) == "/" ]] && kernelpath="" || kernelpath=$(dirname ${kernel})
 
-                echo -e "title\t${title}\nlinux\t${kernel}\n${ucode}initrd\t${initramfs}\noptions\t${sdoptions} ${LINUX_OPTIONS}" > "$(get_entry_root "$esp" "$kernelnum").conf"
-                echo -e "title\t${title}\nlinux\t${kernel}\n${ucode}initrd\t${initramfs}\noptions\t${sdoptions} ${LINUX_FALLBACK_OPTIONS}" > "$(get_entry_root "$esp" "$kernelnum")-fallback.conf"
+                echo -e "title\t${title}\nlinux\t${kernel}\n${ucode}initrd\t${kernelpath}/initramfs-${kernelnum}-${arch}.img\noptions\t${sdoptions} ${LINUX_OPTIONS}" > "$(get_entry_root "$ESP" "$kernelnum").conf"
+                echo -e "title\t${title}\nlinux\t${kernel}\n${ucode}initrd\t${kernelpath}/initramfs-${kernelnum}-${arch}-fallback.img\noptions\t${sdoptions} ${LINUX_FALLBACK_OPTIONS}" > "$(get_entry_root "$ESP" "$kernelnum")-fallback.conf"
+            done < <(find "${ESP}" -maxdepth 4 -type f -name "${KERNEL_PATTERN}" -printf "/%P\n")
 
-            done < <(find "${esp}" -maxdepth 5 -type f -name "${KERNEL_PATTERN}" -printf "/%P\n")
+            if [[ ! "$(ls -A ${ESP}/loader/entries)" ]]; then
+                echo "Error: There are no boot loader entries after entry generation"
+                exit 1
+            fi
 
             # set the default entry in loader.conf
-            entryroot=$(get_entry_root "${esp}")
+            entryroot=$(get_entry_root "${ESP}")
             if [[ ${DEFAULT_ENTRY} == "latest" ]]; then
-                defentry=$(find "${entryroot%/*}" -maxdepth 6 -type f -name "${entryroot##*/}*" -printf "%P\n" | grep -v 'fallback.conf$' | sort -Vr | head -1)
-                sed '/^default/{h;s/.*/default '"${defentry%.*}"'/};${x;/^$/{s//default '"${defentry%.*}"'/;H};x}' -i "${esp}/loader/loader.conf"
+                defentry=$(find "${entryroot%/*}" -maxdepth 4 -type f -name "${entryroot##*/}*" -printf "%P\n" | grep -v 'fallback.conf$' | sort -Vr | head -1)
+                sed '/^default/{h;s/.*/default '"${defentry%.*}"'/};${x;/^$/{s//default '"${defentry%.*}"'/;H};x}' -i "${ESP}/loader/loader.conf"
             elif [[ ${DEFAULT_ENTRY} == "oldest" ]]; then
-                defentry=$(find "${entryroot%/*}" -maxdepth 6 -type f -name "${entryroot##*/}*" -printf "%P\n" | grep -v 'fallback.conf$' | sort -V | head -1 )
-                sed '/^default/{h;s/.*/default '"${defentry%.*}"'/};${x;/^$/{s//default '"${defentry%.*}"'/;H};x}' -i "${esp}/loader/loader.conf"
+                defentry=$(find "${entryroot%/*}" -maxdepth 4 -type f -name "${entryroot##*/}*" -printf "%P\n" | grep -v 'fallback.conf$' | sort -V | head -1 )
+                sed '/^default/{h;s/.*/default '"${defentry%.*}"'/};${x;/^$/{s//default '"${defentry%.*}"'/;H};x}' -i "${ESP}/loader/loader.conf"
             fi
         else
-            echo "Error: ${esp}/loader/entries does not exist"
+            echo "Error: ${ESP}/loader/entries does not exist"
+            exit 1
         fi
     else
-        echo "Error: ${esp}/loader/loader.conf does not exist"
+        echo "Error: ${ESP}/loader/loader.conf does not exist"
+        exit 1
     fi
 }
 
@@ -210,16 +249,13 @@ generate_entries() {
 remove_orphan_entries() {
     [[ ${REMOVE_OBSOLETE,,} != "yes" ]] && return
 
-    # get the esp path
-    esp=$(bootctl -p)
-
     # find and remove all the entries with unmatched kernels
-    for kernel in $(comm -13 <(find "${esp}" -maxdepth 6 -type f -name "${KERNEL_PATTERN}" -printf "/%P\n" | uniq | sort) <(cat "${esp}"/loader/entries/* | grep -i "^linux" | awk '{print $2}' | uniq | sort)); do
+    for kernel in $(comm -13 <(find "${ESP}" -maxdepth 4 -type f -name "${KERNEL_PATTERN}" -printf "/%P\n" | uniq | sort) <(cat "${ESP}"/loader/entries/* | grep -i "^linux" | awk '{print $2}' | uniq | sort)); do
         while read -r entry; do
             # If entry belongs to another distro, don't remove it
             { ! echo "${entry}" | grep -iq "${ENTRY_ROOT}"; } && continue
             remove_entry "${entry}"
-        done < <(grep -l "${kernel}" "${esp}"/loader/entries/*)
+        done < <(grep -l "${kernel}" "${ESP}"/loader/entries/*)
     done
 }
 
@@ -229,7 +265,7 @@ if [[ $EUID -ne 0 ]]; then
    exit 1
 fi
 
-$bootctl status &> /dev/null
+bootctl status &> /dev/null
 if [[ $? == 1 && $1 != "setup" ]]; then
     echo -e "systemd-boot not installed\nTry sdboot-manage setup to install"
     exit 1
@@ -240,7 +276,7 @@ case $1 in
         [[ ${NO_AUTOGEN} != "yes" ]] && generate_entries
         ;;
     autoupdate)
-        [[ ${NO_AUTOUPDATE} != "yes" ]] && $bootctl update
+        [[ ${NO_AUTOUPDATE} != "yes" ]] && bootctl --esp-path=${ESP} update
         ;;
     gen)
         generate_entries
@@ -252,12 +288,12 @@ case $1 in
         setup_sdboot
         ;;
     update)
-        $bootctl update
+        bootctl --esp-path=${ESP} update
         ;;
     *)
         usage
         ;;
-        
+
 esac
 
 exit 0
